apiVersion: v1
kind: Service
metadata:
  name: fatalisa-public-api
spec:
  selector:
    app: fatalisa-public-api
  ports:
    - protocol: TCP
      port: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fatalisa-public-api
  labels:
    app: fatalisa-public-api
spec:
  replicas: 0
  selector:
    matchLabels:
      app: fatalisa-public-api
  template:
    metadata:
      labels:
        app: fatalisa-public-api
    spec:
      containers:
        - name: fatalisa-public-api
          image: docker.io/silencerz23/fatalisa-public-api:latest
          ports:
            - containerPort: 80