apiVersion : apps/v1
kind: Deployment
metadata:
  name: "fatalisa-public-api"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "fatalisa-public-api"
  template:
    metadata:
      labels:
        app: "fatalisa-public-api"
    spec:
      containers:
        - name: "fatalisa-public-api"
          image: "fatalisa.azurecr.io/fatalisa"
          ports:
          - containerPort: 80