apiVersion : apps/v1
kind: Deployment
metadata:
  name: "fatalisa-public-api"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "fatalisa-public-api"
  template:
    metadata:
      labels:
        app: "fatalisa-public-api"
    spec:
      containers:
        - name: "fatalisa-public-api"
          image: "fatalisa.azurecr.io/fatalisa-public-api"
          ports:
          - containerPort: 80
          env:
            - name: TZ
              value: Asia/Jakarta
            - name: PORT
              value: '80'
            # MARIADB
            - name: MARIADB_HOST
              valueFrom:
                secretKeyRef:
                  name: fatalisa
                  key: MARIADB_HOST
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: fatalisa
                  key: MARIADB_USER
            - name: MARIADB_PASS
              valueFrom:
                secretKeyRef:
                  name: fatalisa
                  key: MARIADB_PASS
            - name: MARIADB_DATA
              valueFrom:
                secretKeyRef:
                  name: fatalisa
                  key: MARIADB_DATA
            # POSTGRESQL
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: fatalisa
                  key: POSTGRES_HOST
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: fatalisa
                  key: POSTGRES_USER
            - name: POSTGRES_PASS
              valueFrom:
                secretKeyRef:
                  name: fatalisa
                  key: POSTGRES_PASS
            - name: POSTGRES_DATA
              valueFrom:
                secretKeyRef:
                  name: fatalisa
                  key: POSTGRES_DATA
            # MONGODB
            - name: MONGODB_HOST
              valueFrom:
                secretKeyRef:
                  name: fatalisa
                  key: MONGODB_HOST
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: fatalisa
                  key: MONGODB_USER
            - name: MONGODB_PASS
              valueFrom:
                secretKeyRef:
                  name: fatalisa
                  key: MONGODB_PASS
            - name: MONGODB_DATA
              valueFrom:
                secretKeyRef:
                  name: fatalisa
                  key: MONGODB_DATA
            # REDIS
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: fatalisa
                  key: REDIS_HOST
            - name: REDIS_PASS
              valueFrom:
                secretKeyRef:
                  name: fatalisa
                  key: REDIS_PASS
            # CONSUL
            - name: CONSUL_HOST
              valueFrom:
                secretKeyRef:
                  name: fatalisa
                  key: CONSUL_HOST
            - name: CONSUL_PORT
              valueFrom:
                secretKeyRef:
                  name: fatalisa
                  key: CONSUL_PORT
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            failureThreshold: 1
            periodSeconds: 10