# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Azure-Web-App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_d39fb511d2254ad2adf1e3fa0cc813db }}
        password: ${{ secrets.AzureAppService_ContainerPassword_17e132b8ec4747ac8cab2172f5d28ab1 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d39fb511d2254ad2adf1e3fa0cc813db }}/fatalisa-public-api:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fatalisa-public-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3f547d3c99ab4e6f9ba5072eb45645a0 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d39fb511d2254ad2adf1e3fa0cc813db }}/fatalisa-public-api:${{ github.sha }}'